# Generated by Django 6.0.6 on 2026-07-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('upload_required', models.BooleanField(default=False)),
                ('download_required', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Pending', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Queued', max_length=30)),
                ('uploaded_template', models.FileField(blank=True, null=True, upload_to='task_templates/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='task_outputs/')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dashboard.automationtask')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.taskrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
