# Generated by Django 6.0.6 on 2026-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCRDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('ms_project', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('maintenance_window', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_no', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('risk', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('circle', models.CharField(blank=True, max_length=50, null=True)),
                ('node_details', models.TextField(blank=True, null=True)),
                ('node_count', models.IntegerField(blank=True, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('bpms_cr_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('planning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_executor', models.CharField(blank=True, max_length=100, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_status', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_rollback_cancel', models.TextField(blank=True, null=True)),
                ('technical_validator', models.CharField(blank=True, max_length=100, null=True)),
                ('service_affecting', models.CharField(blank=True, max_length=10, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('test_cases', models.TextField(blank=True, null=True)),
                ('kpi_name', models.TextField(blank=True, null=True)),
                ('kpi_spoc_night', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_spoc_morning', models.CharField(blank=True, max_length=100, null=True)),
                ('inter_domain_activity', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_domain_kpi_required', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_domain_measuring_kpis', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cli_availability', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_start_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_date', models.DateTimeField(blank=True, null=True)),
                ('niam_ticket_required', models.CharField(blank=True, max_length=10, null=True)),
                ('niam_node_type', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_cr_database',
            },
        ),
    ]
