# Generated by Django 6.0.7 on 2026-07-22 10:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('upload_required', models.BooleanField(default=False)),
                ('download_required', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Pending', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='MasterCRDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('ms_project', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('maintenance_window', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_no', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('risk', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('circle', models.CharField(blank=True, max_length=50, null=True)),
                ('node_details', models.TextField(blank=True, null=True)),
                ('node_count', models.IntegerField(blank=True, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('bpms_cr_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('planning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_executor', models.CharField(blank=True, max_length=100, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_status', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_rollback_cancel', models.TextField(blank=True, null=True)),
                ('technical_validator', models.CharField(blank=True, max_length=100, null=True)),
                ('service_affecting', models.CharField(blank=True, max_length=10, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('test_cases', models.TextField(blank=True, null=True)),
                ('kpi_name', models.TextField(blank=True, null=True)),
                ('kpi_spoc_night', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_spoc_morning', models.CharField(blank=True, max_length=100, null=True)),
                ('inter_domain_activity', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_domain_kpi_required', models.CharField(blank=True, max_length=10, null=True)),
                ('inter_domain_measuring_kpis', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cli_availability', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_start_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_date', models.DateTimeField(blank=True, null=True)),
                ('niam_ticket_required', models.CharField(blank=True, max_length=10, null=True)),
                ('niam_node_type', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_cr_database',
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user mail id')),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_signum', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Validator', 'Validator'), ('Night-SPOC', 'Night-SPOC'), ('Executor', 'Executor')], default='Executor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Queued', max_length=30)),
                ('uploaded_template', models.FileField(blank=True, null=True, upload_to='task_templates/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='task_outputs/')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dashboard.automationtask')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.taskrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
