# Generated by Django 6.0.7 on 2026-07-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRWiseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('maintenance_window', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_no', models.CharField(max_length=50, unique=True)),
                ('risk', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('bpms_cr_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('circle', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('technical_validator', models.CharField(blank=True, max_length=100, null=True)),
                ('CR_Hygiene_Checks', models.CharField(blank=True, max_length=100, null=True)),
                ('Install_Test_Plan_Downloads', models.CharField(blank=True, max_length=100, null=True)),
                ('MOP_Attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('CR_Approvals', models.CharField(blank=True, max_length=100, null=True)),
                ('NIAM_Ticket', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cr_wise_status',
            },
        ),
    ]
