# Generated by Django 6.0.7 on 2026-08-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_selecteddatetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='crwisestatus',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='crwisestatus',
            constraint=models.UniqueConstraint(fields=('cr_no',), name='unique_cr_no'),
        ),
    ]
